package homework4.homework.Task2;

public enum Colours {
    INDIAN_RED, SALMON_RED, CRIMSON_RED,
    LEMON_YELLOW, KHAKI_YELLOW, MOCCASIN_YELLOW,
    LIME_GREEN, FOREST_GREEN, OLIVE_GREEN,
    AQUA_BLUE, SKY_BLUE, NAVY_BLUE,
    VANTA_BLACK,
    SNOW_WHITE, BONE_WHITE
}
